// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MatchingResultDTO.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from MatchingResultDTO.proto</summary>
  public static partial class MatchingResultDTOReflection {

    #region Descriptor
    /// <summary>File descriptor for MatchingResultDTO.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MatchingResultDTOReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdNYXRjaGluZ1Jlc3VsdERUTy5wcm90bxIIUHJvdG9jb2wiUAoRUGxheWVy",
            "TWF0Y2hSZXN1bHQSCwoDdWlkGAEgASgEEg8KB3RlYW1faWQYAiABKAUSDQoF",
            "a2lsbHMYAyABKAUSDgoGZGVhdGhzGAQgASgFIscBChFNYXRjaGluZ1Jlc3Vs",
            "dERUTxIPCgdyb29tX2lkGAEgASgEEhQKDGdhbWVfbW9kZV9pZBgCIAEoBRIO",
            "CgZtYXBfaWQYAyABKAUSFgoOd2lubmVyX3RlYW1faWQYBCABKAUSMAoLd2lu",
            "X3BsYXllcnMYBSADKAsyGy5Qcm90b2NvbC5QbGF5ZXJNYXRjaFJlc3VsdBIx",
            "Cgxsb3NlX3BsYXllcnMYBiADKAsyGy5Qcm90b2NvbC5QbGF5ZXJNYXRjaFJl",
            "c3VsdGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.PlayerMatchResult), global::Protocol.PlayerMatchResult.Parser, new[]{ "Uid", "TeamId", "Kills", "Deaths" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.MatchingResultDTO), global::Protocol.MatchingResultDTO.Parser, new[]{ "RoomId", "GameModeId", "MapId", "WinnerTeamId", "WinPlayers", "LosePlayers" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PlayerMatchResult : pb::IMessage<PlayerMatchResult>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlayerMatchResult> _parser = new pb::MessageParser<PlayerMatchResult>(() => new PlayerMatchResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlayerMatchResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protocol.MatchingResultDTOReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerMatchResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerMatchResult(PlayerMatchResult other) : this() {
      uid_ = other.uid_;
      teamId_ = other.teamId_;
      kills_ = other.kills_;
      deaths_ = other.deaths_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerMatchResult Clone() {
      return new PlayerMatchResult(this);
    }

    /// <summary>Field number for the "uid" field.</summary>
    public const int UidFieldNumber = 1;
    private ulong uid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Uid {
      get { return uid_; }
      set {
        uid_ = value;
      }
    }

    /// <summary>Field number for the "team_id" field.</summary>
    public const int TeamIdFieldNumber = 2;
    private int teamId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TeamId {
      get { return teamId_; }
      set {
        teamId_ = value;
      }
    }

    /// <summary>Field number for the "kills" field.</summary>
    public const int KillsFieldNumber = 3;
    private int kills_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Kills {
      get { return kills_; }
      set {
        kills_ = value;
      }
    }

    /// <summary>Field number for the "deaths" field.</summary>
    public const int DeathsFieldNumber = 4;
    private int deaths_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Deaths {
      get { return deaths_; }
      set {
        deaths_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlayerMatchResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlayerMatchResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Uid != other.Uid) return false;
      if (TeamId != other.TeamId) return false;
      if (Kills != other.Kills) return false;
      if (Deaths != other.Deaths) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Uid != 0UL) hash ^= Uid.GetHashCode();
      if (TeamId != 0) hash ^= TeamId.GetHashCode();
      if (Kills != 0) hash ^= Kills.GetHashCode();
      if (Deaths != 0) hash ^= Deaths.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Uid != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Uid);
      }
      if (TeamId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(TeamId);
      }
      if (Kills != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Kills);
      }
      if (Deaths != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Deaths);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Uid != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Uid);
      }
      if (TeamId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(TeamId);
      }
      if (Kills != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Kills);
      }
      if (Deaths != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Deaths);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Uid != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Uid);
      }
      if (TeamId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TeamId);
      }
      if (Kills != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Kills);
      }
      if (Deaths != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Deaths);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlayerMatchResult other) {
      if (other == null) {
        return;
      }
      if (other.Uid != 0UL) {
        Uid = other.Uid;
      }
      if (other.TeamId != 0) {
        TeamId = other.TeamId;
      }
      if (other.Kills != 0) {
        Kills = other.Kills;
      }
      if (other.Deaths != 0) {
        Deaths = other.Deaths;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Uid = input.ReadUInt64();
            break;
          }
          case 16: {
            TeamId = input.ReadInt32();
            break;
          }
          case 24: {
            Kills = input.ReadInt32();
            break;
          }
          case 32: {
            Deaths = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Uid = input.ReadUInt64();
            break;
          }
          case 16: {
            TeamId = input.ReadInt32();
            break;
          }
          case 24: {
            Kills = input.ReadInt32();
            break;
          }
          case 32: {
            Deaths = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MatchingResultDTO : pb::IMessage<MatchingResultDTO>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MatchingResultDTO> _parser = new pb::MessageParser<MatchingResultDTO>(() => new MatchingResultDTO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MatchingResultDTO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protocol.MatchingResultDTOReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MatchingResultDTO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MatchingResultDTO(MatchingResultDTO other) : this() {
      roomId_ = other.roomId_;
      gameModeId_ = other.gameModeId_;
      mapId_ = other.mapId_;
      winnerTeamId_ = other.winnerTeamId_;
      winPlayers_ = other.winPlayers_.Clone();
      losePlayers_ = other.losePlayers_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MatchingResultDTO Clone() {
      return new MatchingResultDTO(this);
    }

    /// <summary>Field number for the "room_id" field.</summary>
    public const int RoomIdFieldNumber = 1;
    private ulong roomId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong RoomId {
      get { return roomId_; }
      set {
        roomId_ = value;
      }
    }

    /// <summary>Field number for the "game_mode_id" field.</summary>
    public const int GameModeIdFieldNumber = 2;
    private int gameModeId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int GameModeId {
      get { return gameModeId_; }
      set {
        gameModeId_ = value;
      }
    }

    /// <summary>Field number for the "map_id" field.</summary>
    public const int MapIdFieldNumber = 3;
    private int mapId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MapId {
      get { return mapId_; }
      set {
        mapId_ = value;
      }
    }

    /// <summary>Field number for the "winner_team_id" field.</summary>
    public const int WinnerTeamIdFieldNumber = 4;
    private int winnerTeamId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int WinnerTeamId {
      get { return winnerTeamId_; }
      set {
        winnerTeamId_ = value;
      }
    }

    /// <summary>Field number for the "win_players" field.</summary>
    public const int WinPlayersFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Protocol.PlayerMatchResult> _repeated_winPlayers_codec
        = pb::FieldCodec.ForMessage(42, global::Protocol.PlayerMatchResult.Parser);
    private readonly pbc::RepeatedField<global::Protocol.PlayerMatchResult> winPlayers_ = new pbc::RepeatedField<global::Protocol.PlayerMatchResult>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Protocol.PlayerMatchResult> WinPlayers {
      get { return winPlayers_; }
    }

    /// <summary>Field number for the "lose_players" field.</summary>
    public const int LosePlayersFieldNumber = 6;
    private static readonly pb::FieldCodec<global::Protocol.PlayerMatchResult> _repeated_losePlayers_codec
        = pb::FieldCodec.ForMessage(50, global::Protocol.PlayerMatchResult.Parser);
    private readonly pbc::RepeatedField<global::Protocol.PlayerMatchResult> losePlayers_ = new pbc::RepeatedField<global::Protocol.PlayerMatchResult>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Protocol.PlayerMatchResult> LosePlayers {
      get { return losePlayers_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MatchingResultDTO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MatchingResultDTO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RoomId != other.RoomId) return false;
      if (GameModeId != other.GameModeId) return false;
      if (MapId != other.MapId) return false;
      if (WinnerTeamId != other.WinnerTeamId) return false;
      if(!winPlayers_.Equals(other.winPlayers_)) return false;
      if(!losePlayers_.Equals(other.losePlayers_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RoomId != 0UL) hash ^= RoomId.GetHashCode();
      if (GameModeId != 0) hash ^= GameModeId.GetHashCode();
      if (MapId != 0) hash ^= MapId.GetHashCode();
      if (WinnerTeamId != 0) hash ^= WinnerTeamId.GetHashCode();
      hash ^= winPlayers_.GetHashCode();
      hash ^= losePlayers_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RoomId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(RoomId);
      }
      if (GameModeId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(GameModeId);
      }
      if (MapId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(MapId);
      }
      if (WinnerTeamId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(WinnerTeamId);
      }
      winPlayers_.WriteTo(output, _repeated_winPlayers_codec);
      losePlayers_.WriteTo(output, _repeated_losePlayers_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RoomId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(RoomId);
      }
      if (GameModeId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(GameModeId);
      }
      if (MapId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(MapId);
      }
      if (WinnerTeamId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(WinnerTeamId);
      }
      winPlayers_.WriteTo(ref output, _repeated_winPlayers_codec);
      losePlayers_.WriteTo(ref output, _repeated_losePlayers_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RoomId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(RoomId);
      }
      if (GameModeId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GameModeId);
      }
      if (MapId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MapId);
      }
      if (WinnerTeamId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(WinnerTeamId);
      }
      size += winPlayers_.CalculateSize(_repeated_winPlayers_codec);
      size += losePlayers_.CalculateSize(_repeated_losePlayers_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MatchingResultDTO other) {
      if (other == null) {
        return;
      }
      if (other.RoomId != 0UL) {
        RoomId = other.RoomId;
      }
      if (other.GameModeId != 0) {
        GameModeId = other.GameModeId;
      }
      if (other.MapId != 0) {
        MapId = other.MapId;
      }
      if (other.WinnerTeamId != 0) {
        WinnerTeamId = other.WinnerTeamId;
      }
      winPlayers_.Add(other.winPlayers_);
      losePlayers_.Add(other.losePlayers_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RoomId = input.ReadUInt64();
            break;
          }
          case 16: {
            GameModeId = input.ReadInt32();
            break;
          }
          case 24: {
            MapId = input.ReadInt32();
            break;
          }
          case 32: {
            WinnerTeamId = input.ReadInt32();
            break;
          }
          case 42: {
            winPlayers_.AddEntriesFrom(input, _repeated_winPlayers_codec);
            break;
          }
          case 50: {
            losePlayers_.AddEntriesFrom(input, _repeated_losePlayers_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            RoomId = input.ReadUInt64();
            break;
          }
          case 16: {
            GameModeId = input.ReadInt32();
            break;
          }
          case 24: {
            MapId = input.ReadInt32();
            break;
          }
          case 32: {
            WinnerTeamId = input.ReadInt32();
            break;
          }
          case 42: {
            winPlayers_.AddEntriesFrom(ref input, _repeated_winPlayers_codec);
            break;
          }
          case 50: {
            losePlayers_.AddEntriesFrom(ref input, _repeated_losePlayers_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
